# Generated by Django 4.2.7 on 2025-12-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                help_text="Максимальная длина 256 символов",
                max_length=256,
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Максимальная длина 256 символов",
                max_length=256,
                verbose_name="Название места",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.location",
                verbose_name="Местоположение",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Максимальная длина 256 символов",
                max_length=256,
                verbose_name="Заголовок",
            ),
        ),
    ]
