# Generated by Django 5.2.8 on 2025-12-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_category_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts_images/", verbose_name="Изображение"
            ),
        ),
    ]
